
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuctionService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuctionService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Item>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findItemByDescription", targetNamespace = "http://service/", className = "service.FindItemByDescription")
    @ResponseWrapper(localName = "findItemByDescriptionResponse", targetNamespace = "http://service/", className = "service.FindItemByDescriptionResponse")
    @Action(input = "http://service/AuctionService/findItemByDescriptionRequest", output = "http://service/AuctionService/findItemByDescriptionResponse")
    public List<Item> findItemByDescription(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns service.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "offerPainting", targetNamespace = "http://service/", className = "service.OfferPainting")
    @ResponseWrapper(localName = "offerPaintingResponse", targetNamespace = "http://service/", className = "service.OfferPaintingResponse")
    @Action(input = "http://service/AuctionService/offerPaintingRequest", output = "http://service/AuctionService/offerPaintingResponse")
    public Item offerPainting(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Category arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns service.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "offerFurniture", targetNamespace = "http://service/", className = "service.OfferFurniture")
    @ResponseWrapper(localName = "offerFurnitureResponse", targetNamespace = "http://service/", className = "service.OfferFurnitureResponse")
    @Action(input = "http://service/AuctionService/offerFurnitureRequest", output = "http://service/AuctionService/offerFurnitureResponse")
    public Item offerFurniture(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Category arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns service.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "offerItem", targetNamespace = "http://service/", className = "service.OfferItem")
    @ResponseWrapper(localName = "offerItemResponse", targetNamespace = "http://service/", className = "service.OfferItemResponse")
    @Action(input = "http://service/AuctionService/offerItemRequest", output = "http://service/AuctionService/offerItemResponse")
    public Item offerItem(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Category arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "revokeItem", targetNamespace = "http://service/", className = "service.RevokeItem")
    @ResponseWrapper(localName = "revokeItemResponse", targetNamespace = "http://service/", className = "service.RevokeItemResponse")
    @Action(input = "http://service/AuctionService/revokeItemRequest", output = "http://service/AuctionService/revokeItemResponse")
    public boolean revokeItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Item arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns service.Bid
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newBid", targetNamespace = "http://service/", className = "service.NewBid")
    @ResponseWrapper(localName = "newBidResponse", targetNamespace = "http://service/", className = "service.NewBidResponse")
    @Action(input = "http://service/AuctionService/newBidRequest", output = "http://service/AuctionService/newBidResponse")
    public Bid newBid(
        @WebParam(name = "arg0", targetNamespace = "")
        Item arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        User arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Money arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItem", targetNamespace = "http://service/", className = "service.GetItem")
    @ResponseWrapper(localName = "getItemResponse", targetNamespace = "http://service/", className = "service.GetItemResponse")
    @Action(input = "http://service/AuctionService/getItemRequest", output = "http://service/AuctionService/getItemResponse")
    public Item getItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
