
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegistrationService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RegistrationService {


    /**
     * 
     * @param arg0
     * @return
     *     returns service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://service/", className = "service.RegisterUser")
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://service/", className = "service.RegisterUserResponse")
    @Action(input = "http://service/RegistrationService/registerUserRequest", output = "http://service/RegistrationService/registerUserResponse")
    public User registerUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://service/", className = "service.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://service/", className = "service.GetUserResponse")
    @Action(input = "http://service/RegistrationService/getUserRequest", output = "http://service/RegistrationService/getUserResponse")
    public User getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
