
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegistrationServiceService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:9000/RegistrationService?wsdl")
public class RegistrationServiceService
    extends Service
{

    private final static URL REGISTRATIONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException REGISTRATIONSERVICESERVICE_EXCEPTION;
    private final static QName REGISTRATIONSERVICESERVICE_QNAME = new QName("http://service/", "RegistrationServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/RegistrationService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGISTRATIONSERVICESERVICE_WSDL_LOCATION = url;
        REGISTRATIONSERVICESERVICE_EXCEPTION = e;
    }

    public RegistrationServiceService() {
        super(__getWsdlLocation(), REGISTRATIONSERVICESERVICE_QNAME);
    }

    public RegistrationServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTRATIONSERVICESERVICE_QNAME, features);
    }

    public RegistrationServiceService(URL wsdlLocation) {
        super(wsdlLocation, REGISTRATIONSERVICESERVICE_QNAME);
    }

    public RegistrationServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTRATIONSERVICESERVICE_QNAME, features);
    }

    public RegistrationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegistrationService
     */
    @WebEndpoint(name = "RegistrationServicePort")
    public RegistrationService getRegistrationServicePort() {
        return super.getPort(new QName("http://service/", "RegistrationServicePort"), RegistrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrationService
     */
    @WebEndpoint(name = "RegistrationServicePort")
    public RegistrationService getRegistrationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "RegistrationServicePort"), RegistrationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTRATIONSERVICESERVICE_EXCEPTION!= null) {
            throw REGISTRATIONSERVICESERVICE_EXCEPTION;
        }
        return REGISTRATIONSERVICESERVICE_WSDL_LOCATION;
    }

}
